(define (problem TPP)
(:domain TPP-PropositionalPreferences)
(:objects
	goods1 goods2 goods3 goods4 goods5 goods6 goods7 goods8 goods9 goods10 goods11 goods12 goods13 - goods
	truck1 truck2 truck3 - truck
	market1 market2 market3 market4 - market
	depot1 depot2 - depot
	level1 level2 level3 level4 level5 level6 - level)

(:init
	(next level1 level0)
	(next level2 level1)
	(next level3 level2)
	(next level4 level3)
	(next level5 level4)
	(next level6 level5)
	(ready-to-load goods1 market1 level0)
	(ready-to-load goods1 market2 level0)
	(ready-to-load goods1 market3 level0)
	(ready-to-load goods1 market4 level0)
	(ready-to-load goods1 depot1 level0)
	(ready-to-load goods1 depot2 level0)
	(ready-to-load goods2 market1 level0)
	(ready-to-load goods2 market2 level0)
	(ready-to-load goods2 market3 level0)
	(ready-to-load goods2 market4 level0)
	(ready-to-load goods2 depot1 level0)
	(ready-to-load goods2 depot2 level0)
	(ready-to-load goods3 market1 level0)
	(ready-to-load goods3 market2 level0)
	(ready-to-load goods3 market3 level0)
	(ready-to-load goods3 market4 level0)
	(ready-to-load goods3 depot1 level0)
	(ready-to-load goods3 depot2 level0)
	(ready-to-load goods4 market1 level0)
	(ready-to-load goods4 market2 level0)
	(ready-to-load goods4 market3 level0)
	(ready-to-load goods4 market4 level0)
	(ready-to-load goods4 depot1 level0)
	(ready-to-load goods4 depot2 level0)
	(ready-to-load goods5 market1 level0)
	(ready-to-load goods5 market2 level0)
	(ready-to-load goods5 market3 level0)
	(ready-to-load goods5 market4 level0)
	(ready-to-load goods5 depot1 level0)
	(ready-to-load goods5 depot2 level0)
	(ready-to-load goods6 market1 level0)
	(ready-to-load goods6 market2 level0)
	(ready-to-load goods6 market3 level0)
	(ready-to-load goods6 market4 level0)
	(ready-to-load goods6 depot1 level0)
	(ready-to-load goods6 depot2 level0)
	(ready-to-load goods7 market1 level0)
	(ready-to-load goods7 market2 level0)
	(ready-to-load goods7 market3 level0)
	(ready-to-load goods7 market4 level0)
	(ready-to-load goods7 depot1 level0)
	(ready-to-load goods7 depot2 level0)
	(ready-to-load goods8 market1 level0)
	(ready-to-load goods8 market2 level0)
	(ready-to-load goods8 market3 level0)
	(ready-to-load goods8 market4 level0)
	(ready-to-load goods8 depot1 level0)
	(ready-to-load goods8 depot2 level0)
	(ready-to-load goods9 market1 level0)
	(ready-to-load goods9 market2 level0)
	(ready-to-load goods9 market3 level0)
	(ready-to-load goods9 market4 level0)
	(ready-to-load goods9 depot1 level0)
	(ready-to-load goods9 depot2 level0)
	(ready-to-load goods10 market1 level0)
	(ready-to-load goods10 market2 level0)
	(ready-to-load goods10 market3 level0)
	(ready-to-load goods10 market4 level0)
	(ready-to-load goods10 depot1 level0)
	(ready-to-load goods10 depot2 level0)
	(ready-to-load goods11 market1 level0)
	(ready-to-load goods11 market2 level0)
	(ready-to-load goods11 market3 level0)
	(ready-to-load goods11 market4 level0)
	(ready-to-load goods11 depot1 level0)
	(ready-to-load goods11 depot2 level0)
	(ready-to-load goods12 market1 level0)
	(ready-to-load goods12 market2 level0)
	(ready-to-load goods12 market3 level0)
	(ready-to-load goods12 market4 level0)
	(ready-to-load goods12 depot1 level0)
	(ready-to-load goods12 depot2 level0)
	(ready-to-load goods13 market1 level0)
	(ready-to-load goods13 market2 level0)
	(ready-to-load goods13 market3 level0)
	(ready-to-load goods13 market4 level0)
	(ready-to-load goods13 depot1 level0)
	(ready-to-load goods13 depot2 level0)
	(stored goods1 level0)
	(stored goods2 level0)
	(stored goods3 level0)
	(stored goods4 level0)
	(stored goods5 level0)
	(stored goods6 level0)
	(stored goods7 level0)
	(stored goods8 level0)
	(stored goods9 level0)
	(stored goods10 level0)
	(stored goods11 level0)
	(stored goods12 level0)
	(stored goods13 level0)
	(loaded goods1 truck1 level0)
	(loaded goods1 truck2 level0)
	(loaded goods1 truck3 level0)
	(loaded goods2 truck1 level0)
	(loaded goods2 truck2 level0)
	(loaded goods2 truck3 level0)
	(loaded goods3 truck1 level0)
	(loaded goods3 truck2 level0)
	(loaded goods3 truck3 level0)
	(loaded goods4 truck1 level0)
	(loaded goods4 truck2 level0)
	(loaded goods4 truck3 level0)
	(loaded goods5 truck1 level0)
	(loaded goods5 truck2 level0)
	(loaded goods5 truck3 level0)
	(loaded goods6 truck1 level0)
	(loaded goods6 truck2 level0)
	(loaded goods6 truck3 level0)
	(loaded goods7 truck1 level0)
	(loaded goods7 truck2 level0)
	(loaded goods7 truck3 level0)
	(loaded goods8 truck1 level0)
	(loaded goods8 truck2 level0)
	(loaded goods8 truck3 level0)
	(loaded goods9 truck1 level0)
	(loaded goods9 truck2 level0)
	(loaded goods9 truck3 level0)
	(loaded goods10 truck1 level0)
	(loaded goods10 truck2 level0)
	(loaded goods10 truck3 level0)
	(loaded goods11 truck1 level0)
	(loaded goods11 truck2 level0)
	(loaded goods11 truck3 level0)
	(loaded goods12 truck1 level0)
	(loaded goods12 truck2 level0)
	(loaded goods12 truck3 level0)
	(loaded goods13 truck1 level0)
	(loaded goods13 truck2 level0)
	(loaded goods13 truck3 level0)
	(connected market1 market2)
	(connected market1 market3)
	(connected market1 market4)
	(connected market2 market1)
	(connected market2 market3)
	(connected market2 market4)
	(connected market3 market1)
	(connected market3 market2)
	(connected market3 market4)
	(connected market4 market1)
	(connected market4 market2)
	(connected market4 market3)
	(connected depot1 market1)
	(connected market1 depot1)
	(connected depot1 market2)
	(connected market2 depot1)
	(connected depot1 market3)
	(connected market3 depot1)
	(connected depot1 market4)
	(connected market4 depot1)
	(connected depot2 market1)
	(connected market1 depot2)
	(connected depot2 market2)
	(connected market2 depot2)
	(connected depot2 market3)
	(connected market3 depot2)
	(connected depot2 market4)
	(connected market4 depot2)
	(on-sale goods1 market1 level0)
	(on-sale goods2 market1 level1)
	(on-sale goods3 market1 level3)
	(on-sale goods4 market1 level2)
	(on-sale goods5 market1 level1)
	(on-sale goods6 market1 level2)
	(on-sale goods7 market1 level1)
	(on-sale goods8 market1 level0)
	(on-sale goods9 market1 level1)
	(on-sale goods10 market1 level0)
	(on-sale goods11 market1 level3)
	(on-sale goods12 market1 level0)
	(on-sale goods13 market1 level3)
	(on-sale goods1 market2 level0)
	(on-sale goods2 market2 level0)
	(on-sale goods3 market2 level2)
	(on-sale goods4 market2 level0)
	(on-sale goods5 market2 level0)
	(on-sale goods6 market2 level0)
	(on-sale goods7 market2 level0)
	(on-sale goods8 market2 level1)
	(on-sale goods9 market2 level1)
	(on-sale goods10 market2 level2)
	(on-sale goods11 market2 level0)
	(on-sale goods12 market2 level3)
	(on-sale goods13 market2 level0)
	(on-sale goods1 market3 level1)
	(on-sale goods2 market3 level1)
	(on-sale goods3 market3 level1)
	(on-sale goods4 market3 level2)
	(on-sale goods5 market3 level2)
	(on-sale goods6 market3 level3)
	(on-sale goods7 market3 level2)
	(on-sale goods8 market3 level1)
	(on-sale goods9 market3 level3)
	(on-sale goods10 market3 level1)
	(on-sale goods11 market3 level2)
	(on-sale goods12 market3 level3)
	(on-sale goods13 market3 level2)
	(on-sale goods1 market4 level0)
	(on-sale goods2 market4 level1)
	(on-sale goods3 market4 level0)
	(on-sale goods4 market4 level0)
	(on-sale goods5 market4 level0)
	(on-sale goods6 market4 level0)
	(on-sale goods7 market4 level0)
	(on-sale goods8 market4 level0)
	(on-sale goods9 market4 level1)
	(on-sale goods10 market4 level0)
	(on-sale goods11 market4 level1)
	(on-sale goods12 market4 level0)
	(on-sale goods13 market4 level1)
	(at truck1 depot1)
	(at truck2 depot2)
	(at truck3 depot2))

(:goal (and
))(:constraints (and
(sometime-before (and (not (= level1 level0)) (stored goods5 level1)) (stored goods11 level1))
(sometime-before (and (not (= level3 level0)) (stored goods5 level3)) (stored goods11 level3))
(sometime-before (and (not (= level2 level0)) (stored goods5 level2)) (stored goods11 level2))
(sometime-before (and (not (= level5 level0)) (stored goods5 level5)) (stored goods11 level5))
(sometime-before (and (not (= level4 level0)) (stored goods5 level4)) (stored goods11 level4))
(sometime-before (and (not (= level6 level0)) (stored goods5 level6)) (stored goods11 level6))
(at-most-once (exists (?l - level) (and (loaded goods9 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods8 truck3 ?l) (not (= ?l level0)))) )
(always (or (not (and (at truck3 market4) (at truck1 market4))) (= truck3 truck1)))
(always (or (not (and (at truck1 market1) (at truck2 market1))) (= truck1 truck2)))
(at-most-once (exists (?l - level) (and (loaded goods7 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods7 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods8 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods8 truck1 ?l) (not (= ?l level0)))) )
(always (or (not (and (at truck1 market1) (at truck3 market1))) (= truck1 truck3)))
(always (or (not (and (at truck3 market4) (at truck2 market4))) (= truck3 truck2)))
(at-most-once (at truck3 market3) )
(at-most-once (at truck3 market2) )
(at-most-once (at truck3 market4) )
(always (or (not (and (at truck1 market3) (at truck3 market3))) (= truck1 truck3)))
(always (or (not (and (at truck1 market2) (at truck3 market2))) (= truck1 truck3)))
(at-most-once (exists (?l - level) (and (loaded goods11 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods11 truck3 ?l) (not (= ?l level0)))) )
(always (or (not (and (at truck3 market3) (at truck2 market3))) (= truck3 truck2)))
(always (or (not (and (at truck3 market2) (at truck2 market2))) (= truck3 truck2)))
(always (or (not (and (at truck3 market4) (at truck3 market4))) (= truck3 truck3)))
(always (or (not (and (at truck3 market2) (at truck3 market2))) (= truck3 truck3)))
(always (or (not (and (at truck3 market3) (at truck3 market3))) (= truck3 truck3)))
(always (or (not (and (at truck2 market4) (at truck3 market4))) (= truck2 truck3)))
(always (or (not (and (at truck3 market1) (at truck3 market1))) (= truck3 truck3)))
(always (or (not (and (at truck2 market2) (at truck3 market2))) (= truck2 truck3)))
(always (or (not (and (at truck2 market3) (at truck3 market3))) (= truck2 truck3)))
(always (or (not (and (at truck2 market4) (at truck1 market4))) (= truck2 truck1)))
(always (or (not (and (at truck3 market1) (at truck1 market1))) (= truck3 truck1)))
(always (or (not (and (at truck2 market2) (at truck1 market2))) (= truck2 truck1)))
(always (or (not (and (at truck2 market3) (at truck1 market3))) (= truck2 truck1)))
(always (or (not (and (at truck1 market4) (at truck1 market4))) (= truck1 truck1)))
(always (or (not (and (at truck2 market1) (at truck1 market1))) (= truck2 truck1)))
(always (or (not (and (at truck1 market2) (at truck1 market2))) (= truck1 truck1)))
(always (or (not (and (at truck1 market3) (at truck1 market3))) (= truck1 truck1)))
(always (or (not (and (at truck1 market1) (at truck1 market1))) (= truck1 truck1)))
(always (or (not (and (at truck2 market1) (at truck3 market1))) (= truck2 truck3)))
(always (or (not (and (at truck1 market4) (at truck3 market4))) (= truck1 truck3)))
(at-most-once (exists (?l - level) (and (loaded goods13 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods13 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods12 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods13 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods12 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods12 truck2 ?l) (not (= ?l level0)))) )
(always (or (not (and (at truck3 market1) (at truck2 market1))) (= truck3 truck2)))
(always (or (not (and (at truck2 market4) (at truck2 market4))) (= truck2 truck2)))
(at-most-once (exists (?l - level) (and (loaded goods10 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods11 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (at truck1 market1) )
(at-most-once (at truck1 market3) )
(at-most-once (at truck1 market2) )
(at-most-once (at truck2 market1) )
(at-most-once (at truck1 market4) )
(at-most-once (at truck2 market3) )
(at-most-once (at truck2 market2) )
(at-most-once (at truck3 market1) )
(at-most-once (at truck2 market4) )
(always (or (not (and (at truck2 market2) (at truck2 market2))) (= truck2 truck2)))
(always (or (not (and (at truck2 market3) (at truck2 market3))) (= truck2 truck2)))
(at-most-once (exists (?l - level) (and (loaded goods10 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods10 truck1 ?l) (not (= ?l level0)))) )
(always (or (not (and (at truck3 market2) (at truck1 market2))) (= truck3 truck1)))
(always (or (not (and (at truck3 market3) (at truck1 market3))) (= truck3 truck1)))
(at-most-once (exists (?l - level) (and (loaded goods9 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods9 truck2 ?l) (not (= ?l level0)))) )
(always (or (not (and (at truck1 market2) (at truck2 market2))) (= truck1 truck2)))
(always (or (not (and (at truck1 market3) (at truck2 market3))) (= truck1 truck2)))
(always (or (not (and (at truck1 market4) (at truck2 market4))) (= truck1 truck2)))
(always (or (not (and (at truck2 market1) (at truck2 market1))) (= truck2 truck2)))
(sometime (exists (?g - goods ?l - level) (and (loaded ?g truck3 ?l) (not (= ?l level0)))))
(sometime (exists (?g - goods ?l - level) (and (loaded ?g truck2 ?l) (not (= ?l level0)))))
(sometime (exists (?g - goods ?l - level) (and (loaded ?g truck1 ?l) (not (= ?l level0)))))
(at-most-once (exists (?l - level) (and (loaded goods6 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods7 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods4 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods4 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods4 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods5 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods5 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods5 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods6 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods6 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods3 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods3 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods2 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods3 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods2 truck1 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods2 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods1 truck2 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods1 truck3 ?l) (not (= ?l level0)))) )
(at-most-once (exists (?l - level) (and (loaded goods1 truck1 ?l) (not (= ?l level0)))) )
 )))