(define (problem grounded-STRIPS-OS-SOFTPREFERENCES-WBOP_10_10-11)
(:domain grounded-STRIPS-OPENSTACKS-SOFTPREFERENCES)
(:init
(NOT-STARTED-O1)
(NOT-STARTED-O2)
(NOT-STARTED-O3)
(NOT-STARTED-O4)
(NOT-STARTED-O5)
(NOT-STARTED-O6)
(NOT-STARTED-O7)
(NOT-STARTED-O8)
(NOT-STARTED-O9)
(NOT-STARTED-O10)
(NOT-MADE-P1)
(NOT-MADE-P2)
(NOT-MADE-P3)
(NOT-MADE-P4)
(NOT-MADE-P5)
(NOT-MADE-P6)
(NOT-MADE-P7)
(NOT-MADE-P8)
(NOT-MADE-P9)
(NOT-MADE-P10)
(WAITING-O10)
(WAITING-O9)
(WAITING-O8)
(WAITING-O7)
(WAITING-O6)
(WAITING-O5)
(WAITING-O4)
(WAITING-O3)
(WAITING-O2)
(WAITING-O1)
(STACKS-IN-USE-N0)
)
(:goal (and 
(shipped-o10 )
(shipped-o9 )
(shipped-o8 )
(shipped-o7 )
(shipped-o6 )
(shipped-o5 )
(shipped-o4 )
(shipped-o3 )
(shipped-o2 )
(shipped-o1 )
(delivered-o9-p4 )
(delivered-o5-p2 )
(and (delivered-o10-p5 ) (delivered-o10-p1 ))
(and (delivered-o10-p6 ) (delivered-o10-p5 ) (delivered-o10-p1 ))
(delivered-o10-p1 )
(delivered-o3-p1 )
(and (delivered-o9-p7 ) (delivered-o9-p4 ))
(and (delivered-o3-p8 ) (delivered-o3-p2 ) (delivered-o3-p1 ))
(and (delivered-o3-p2 ) (delivered-o3-p1 ))
(and (delivered-o1-p9 ) (delivered-o1-p6 ) (delivered-o1-p1 ))
(and (delivered-o1-p6 ) (delivered-o1-p1 ))
(delivered-o1-p1 )
(delivered-o7-p3 )
(and (delivered-o7-p7 ) (delivered-o7-p4 ) (delivered-o7-p3 ))
(and (delivered-o7-p4 ) (delivered-o7-p3 ))
(and (delivered-o6-p8 ) (delivered-o6-p7 ))
(and (delivered-o6-p10 ) (delivered-o6-p8 ) (delivered-o6-p7 ))
(delivered-o6-p7 )
(delivered-o4-p3 )
(and (delivered-o4-p4 ) (delivered-o4-p3 ))
(and (delivered-o4-p10 ) (delivered-o4-p4 ) (delivered-o4-p3 ))
(delivered-o8-p3 )
(and (delivered-o2-p8 ) (delivered-o2-p2 ))
(delivered-o2-p2 )
))(:constraints (and 
(always (not (stacks-in-use-n10 )))
(always (not (stacks-in-use-n8 )))
(always (not (stacks-in-use-n9 )))
(always (not (stacks-in-use-n6 )))
(always (not (stacks-in-use-n7 )))
(always (not (stacks-in-use-n5 )))
 )))